services:
  - type: web
    name: marketing-generator
    env: python
    plan: free
    runtime: python-3.11.9
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --bind 0.0.0.0:$PORT app:app
    healthCheckPath: /
    envVars:
      - key: GEMINI_API_KEY
        sync: false
      - key: FLASK_ENV
        value: production
      - key: FLASK_DEBUG
        value: False
